version: "3"
services:
  database:
    container_name: "cuic_demo_db"
    image: "postgres:11-alpine"
    ports:
      - "45432:5432"
    environment:
      - "POSTGRES_USER=dev"
      - "POSTGRES_PASSWORD=ts3rs"
      - "POSTGRES_DB=demo"
